### ISSUE TITLE
Is this the SSDT for ThinkPad X1 carbon 2015? 这是ThinkPad X1 Carbon 2015的SSDT吗？

### ISSUE THREAD

**Issue by vihor3** [iphone2ch/Lenovo-Thinkpad-X1C3#1]
Is this the SSDT for ThinkPad X1 carbon 2015? 这是ThinkPad X1 Carbon 2015的SSDT吗？

**Comment by vihor3** [comment]
Or Is this is the SSDT for Thinkpad X1 Carbon 3th?

**Comment by sakurahack** [comment]
Yes, this is thinkpad x1 carbon 2015 3rd generation
is.

See also here.
https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x1-carbon-gen-3-2015-model-using-clover-uefi.251383/
